name: Build

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_and_apk:
    name: "Local tests and APKs"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: run
        run: |
          chmod +x ./clone.sh
          ./clone.sh

      - name: Upload build outputs
        uses: actions/upload-artifact@v4
        with:
          name: arm
          path: '/tmp/python3_11_arm.zip'